#! /bin/bash
NAME="dnvim"
if docker container inspect $NAME >/dev/null 2>&1; then
  echo "Attaching to running container"
  docker exec -it --privileged $NAME zsh
else
  echo "Creating container"
  docker run --name $NAME -it --rm --privileged -v $(pwd):/home nvim:latest
fi

