require "user.plugins"
require "user.options"
require "user.keymaps"
require "user.cmp"
require "user.lsp"
require "user.snippets"
require "user.telescope"
require "user.treesitter"
require "user.git"
require "user.null"

